#!/bin/bash
# FastAPI utility script

# Function to create a new FastAPI project structure
create_project() {
  local project_name=$1
  local project_dir=$project_name

  if [ -z "$project_name" ]; then
    echo "Usage: $0 create-project <project-name>"
    exit 1
  fi

  mkdir -p "$project_dir"/{routers,models,schemas,dependencies,utils}

  # Create main.py
  cat > "$project_dir/main.py" << 'EOF'
from fastapi import FastAPI
from routers import items, users

app = FastAPI(
    title="My API",
    description="FastAPI project generated by FastAPI Builder skill",
    version="1.0.0"
)

app.include_router(items.router)
app.include_router(users.router)

@app.get("/")
def read_root():
    return {"Hello": "World"}
EOF

  # Create requirements.txt
  cat > "$project_dir/requirements.txt" << 'EOF'
fastapi==0.104.1
uvicorn[standard]==0.24.0
pydantic==2.5.0
sqlalchemy==2.0.23
python-multipart==0.0.6
python-jose[cryptography]==3.3.0
passlib[bcrypt]==1.7.4
python-dotenv==1.0.0
pytest==7.4.3
httpx==0.25.2
EOF

  # Create basic router
  cat > "$project_dir/routers/items.py" << 'EOF'
from fastapi import APIRouter, Depends, HTTPException
from typing import List, Optional
from schemas.item import Item, ItemCreate
from dependencies import get_db
from models.item import Item as ItemModel
from sqlalchemy.orm import Session

router = APIRouter(
    prefix="/items",
    tags=["items"],
    responses={404: {"description": "Not found"}}
)

@router.get("/", response_model=List[Item])
def read_items(skip: int = 0, limit: int = 100, db: Session = Depends(get_db)):
    items = db.query(ItemModel).offset(skip).limit(limit).all()
    return items

@router.post("/", response_model=Item)
def create_item(item: ItemCreate, db: Session = Depends(get_db)):
    db_item = ItemModel(**item.model_dump())
    db.add(db_item)
    db.commit()
    db.refresh(db_item)
    return db_item
EOF

  # Create basic model
  cat > "$project_dir/models/item.py" << 'EOF'
from sqlalchemy import Column, Integer, String, Float
from database import Base

class Item(Base):
    __tablename__ = "items"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, index=True)
    description = Column(String, index=True)
    price = Column(Float)
    tax = Column(Float)
EOF

  # Create basic schema
  cat > "$project_dir/schemas/item.py" << 'EOF'
from pydantic import BaseModel
from typing import Optional

class ItemBase(BaseModel):
    name: str
    description: Optional[str] = None
    price: float
    tax: Optional[float] = None

class ItemCreate(ItemBase):
    pass

class Item(ItemBase):
    id: int

    class Config:
        from_attributes = True
EOF

  # Create database setup
  cat > "$project_dir/database.py" << 'EOF'
from sqlalchemy import create_engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker
import os

DATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///./test.db")

engine = create_engine(DATABASE_URL)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

Base = declarative_base()

def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
EOF

  echo "Created FastAPI project: $project_dir"
  echo "To run the project:"
  echo "  cd $project_dir"
  echo "  pip install -r requirements.txt"
  echo "  uvicorn main:app --reload"
}

# Function to create a new API endpoint
create_endpoint() {
  local endpoint_name=$1
  local router_file="routers/$endpoint_name.py"

  if [ -z "$endpoint_name" ]; then
    echo "Usage: $0 create-endpoint <endpoint-name>"
    exit 1
  fi

  mkdir -p routers

  cat > "$router_file" << EOF
from fastapi import APIRouter, Depends, HTTPException
from typing import List
from schemas.${endpoint_name} import ${endpoint_name.capitalize()}, ${endpoint_name.capitalize()}Create
from dependencies import get_db
from sqlalchemy.orm import Session

router = APIRouter(
    prefix="/${endpoint_name}",
    tags=["${endpoint_name}"],
    responses={404: {"description": "Not found"}}
)

@router.get("/", response_model=List[${endpoint_name.capitalize()}])
def read_${endpoint_name}(skip: int = 0, limit: int = 100, db: Session = Depends(get_db)):
    # Implementation here
    return []

@router.post("/", response_model=${endpoint_name.capitalize()})
def create_${endpoint_name}(item: ${endpoint_name.capitalize()}Create, db: Session = Depends(get_db)):
    # Implementation here
    return item
EOF

  echo "Created endpoint: $router_file"
}

# Main script
case $1 in
  "create-project")
    if [ -z "$2" ]; then
      echo "Usage: $0 create-project <project-name>"
      exit 1
    fi
    create_project "$2"
    ;;
  "create-endpoint")
    if [ -z "$2" ]; then
      echo "Usage: $0 create-endpoint <endpoint-name>"
      exit 1
    fi
    create_endpoint "$2"
    ;;
  *)
    echo "Usage: $0 {create-project|create-endpoint} [name]"
    echo "  create-project: Create a new FastAPI project structure"
    echo "  create-endpoint: Create a new API endpoint"
    exit 1
    ;;
esac