openapi: 3.0.0
info:
  title: Todo Task API
  description: API for managing todo tasks in the full-stack todo application
  version: 1.0.0
servers:
  - url: http://localhost:8000/api/v1
    description: Local development server

paths:
  /tasks:
    get:
      summary: Get all tasks
      description: Retrieve a list of all todo tasks
      responses:
        '200':
          description: A list of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    post:
      summary: Create a new task
      description: Create a new todo task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreate'
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Invalid input data

  /tasks/{id}:
    get:
      summary: Get a task by ID
      description: Retrieve a specific todo task by its ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Task details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Task not found
    put:
      summary: Update a task
      description: Update an existing todo task
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdate'
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Invalid input data
        '404':
          description: Task not found
    delete:
      summary: Delete a task
      description: Delete a specific todo task by its ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Task deleted successfully
        '404':
          description: Task not found

components:
  schemas:
    Task:
      type: object
      required:
        - id
        - title
        - is_completed
        - created_at
        - updated_at
      properties:
        id:
          type: string
          description: Unique identifier for the task
        title:
          type: string
          description: Title of the task
          maxLength: 255
        description:
          type: string
          description: Detailed description of the task
          nullable: true
        is_completed:
          type: boolean
          description: Whether the task is completed
          default: false
        created_at:
          type: string
          format: date-time
          description: Timestamp when the task was created
        updated_at:
          type: string
          format: date-time
          description: Timestamp when the task was last updated
    TaskCreate:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          description: Title of the task
          maxLength: 255
        description:
          type: string
          description: Detailed description of the task
          nullable: true
    TaskUpdate:
      type: object
      properties:
        title:
          type: string
          description: Title of the task
          maxLength: 255
          nullable: true
        description:
          type: string
          description: Detailed description of the task
          nullable: true
        is_completed:
          type: boolean
          description: Whether the task is completed