// pages/{{pageName}}.jsx
import Head from 'next/head';
import React from 'react';

export default function {{pageName}}({ data }) {
  return (
    <div>
      <Head>
        <title>{{pageName}}</title>
        <meta name="description" content="Generated by Next.js Builder skill" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {/* Page content */}
      </main>
    </div>
  );
}

// Optional: Add data fetching method based on requirements
// export async function getStaticProps() {
//   // Fetch data here
//   return {
//     props: {
//       data: {},
//     },
//     // revalidate: 60, // For SSG with revalidation
//   };
// }

// For dynamic routes:
// export async function getStaticPaths() {
//   return {
//     paths: [],
//     fallback: 'blocking',
//   };
// }