openapi: 3.0.0
info:
  title: Todo Task API with Authentication
  description: API for managing todo tasks in the full-stack todo application with JWT-based authentication
  version: 1.0.0
servers:
  - url: http://localhost:8000/api/v1
    description: Local development server

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Task:
      type: object
      required:
        - id
        - title
        - is_completed
        - user_id
        - created_at
        - updated_at
      properties:
        id:
          type: string
          description: Unique identifier for the task
        title:
          type: string
          description: Title of the task
          maxLength: 255
        description:
          type: string
          description: Detailed description of the task
          nullable: true
        is_completed:
          type: boolean
          description: Whether the task is completed
          default: false
        user_id:
          type: string
          description: Unique identifier for the user who owns this task
        created_at:
          type: string
          format: date-time
          description: Timestamp when the task was created
        updated_at:
          type: string
          format: date-time
          description: Timestamp when the task was last updated
    TaskCreate:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          description: Title of the task
          maxLength: 255
        description:
          type: string
          description: Detailed description of the task
          nullable: true
    TaskUpdate:
      type: object
      properties:
        title:
          type: string
          description: Title of the task
          maxLength: 255
          nullable: true
        description:
          type: string
          description: Detailed description of the task
          nullable: true
        is_completed:
          type: boolean
          description: Whether the task is completed
    User:
      type: object
      required:
        - id
        - email
        - created_at
        - updated_at
      properties:
        id:
          type: string
          description: Unique identifier for the user
        email:
          type: string
          description: User's email address
        name:
          type: string
          description: User's display name
          nullable: true
        created_at:
          type: string
          format: date-time
          description: Timestamp when the user account was created
        updated_at:
          type: string
          format: date-time
          description: Timestamp when the user account was last updated

paths:
  /users/{user_id}/tasks:
    get:
      summary: Get all tasks for a specific user
      description: Retrieve a list of all todo tasks for a specific user. Requires authentication.
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
          description: The ID of the user whose tasks to retrieve
      security:
        - BearerAuth: []
      responses:
        '200':
          description: A list of tasks for the specified user
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized - Missing or invalid JWT token
        '403':
          description: Forbidden - User ID in JWT does not match path parameter
        '404':
          description: User not found
    post:
      summary: Create a new task for a specific user
      description: Create a new todo task for a specific user. Requires authentication.
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
          description: The ID of the user to create the task for
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreate'
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Invalid input data
        '401':
          description: Unauthorized - Missing or invalid JWT token
        '403':
          description: Forbidden - User ID in JWT does not match path parameter
        '404':
          description: User not found

  /users/{user_id}/tasks/{id}:
    get:
      summary: Get a specific task for a user
      description: Retrieve a specific todo task by its ID for a specific user. Requires authentication.
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
          description: The ID of the user whose task to retrieve
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The ID of the task to retrieve
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Task details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized - Missing or invalid JWT token
        '403':
          description: Forbidden - User ID in JWT does not match path parameter
        '404':
          description: Task not found
    put:
      summary: Update a specific task for a user
      description: Update an existing todo task for a specific user. Requires authentication.
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
          description: The ID of the user whose task to update
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The ID of the task to update
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdate'
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Invalid input data
        '401':
          description: Unauthorized - Missing or invalid JWT token
        '403':
          description: Forbidden - User ID in JWT does not match path parameter
        '404':
          description: Task not found
    delete:
      summary: Delete a specific task for a user
      description: Delete a specific todo task by its ID for a specific user. Requires authentication.
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
          description: The ID of the user whose task to delete
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The ID of the task to delete
      security:
        - BearerAuth: []
      responses:
        '204':
          description: Task deleted successfully
        '401':
          description: Unauthorized - Missing or invalid JWT token
        '403':
          description: Forbidden - User ID in JWT does not match path parameter
        '404':
          description: Task not found